name: Tests

on:
  push:
    paths-ignore:
      - "*.md"
  pull_request:
    paths-ignore:
      - "*.md"

jobs:
  tests:
    timeout-minutes: ${{ fromJSON(vars.GHA_DEFAULT_TIMEOUT) }}
    name: Tests
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
        - golang: '^1.18'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ matrix.golang }}"
          cache: true
      - run: go version

      - name: Build
        run: make
